imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.native_file
        save_path: '%kernel.root_dir%/sessions'
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form_themes:
      - bootstrap_3_layout.html.twig
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        company: "%company%"
        phrase:  "%phrase%"
        version: "%version%"
        teamcreator: "%teamcreator%"
        enviroment: "%enviroment%"
        color: "%color%"
        importacao: "%importacao%"
        gestao_dados: "%gestao_dados%"
        gestao_ip: "%gestao_ip%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
          bit: boolean
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        #Stof\Gedmo
        mappings:
           loggable:
               type: annotation
               alias: Gedmo
               prefix: Gedmo\Loggable\Entity
               dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#upload
vich_uploader:
    db_driver: orm
    mappings:
      mapeamento_equipamento:
          uri_prefix: "%base_url%/anexos/equipamentos"
          upload_destination: "%kernel.root_dir%/../web/anexos/equipamentos"
          namer: vich_uploader.namer_origname
      mapeamento_acompanhamento:
          uri_prefix: "%base_url%/anexos/acompanhamentos"
          upload_destination: "%kernel.root_dir%/../web/anexos/acompanhamentos"
          namer: vich_uploader.namer_origname
      mapeamento_restore:
          uri_prefix: "%base_url%/anexos/restore"
          upload_destination: "%kernel.root_dir%/../web/anexos/restore"
          namer: vich_uploader.namer_origname
      mapeamento_backup:
          uri_prefix: "%base_url%/anexos/backup"
          upload_destination: "%kernel.root_dir%/../web/anexos/backup"
          namer: vich_uploader.namer_origname
      mapeamento_backup_compartilhado:
          uri_prefix: "%base_url%/anexos/backupcompartilhado"
          upload_destination: "%kernel.root_dir%/../web/anexos/backupcompartilhado"
          namer: vich_uploader.namer_origname

#QrCode
endroid_qr_code:
    writer: 'png'
    size: 150
    margin: 10
    foreground_color: { r: 0, g: 0, b: 0 }
    background_color: { r: 255, g: 255, b: 255 }
    error_correction_level: low # low, medium, quartile or high
    encoding: UTF-8
    label: ''
    label_font_size: 20
    label_alignment: left # left, center or right
    label_margin: { b: 20 }
    #logo_path: '%kernel.root_dir%/../vendor/endroid/qrcode/assets/symfony.png'
    logo_width: 150
    validate_result: false # checks if the result is readable