mrs_inventario_status_ip:
    resource: "@MRSInventarioBundle/Controller/StatusIpController.php"
    type:     annotation

mrs_inventario_tipo_acesso_ip:
    resource: "@MRSInventarioBundle/Controller/TipoAcessoIpController.php"
    type:     annotation

mrs_inventario_endereco_ip:
    resource: "@MRSInventarioBundle/Controller/EnderecoIpController.php"
    type:     annotation

mrs_inventario_anexo_acompanhamento:
    resource: "@MRSInventarioBundle/Controller/AnexoAcompanhamentoController.php"
    type:     annotation

mrs_inventario_anexo:
    resource: "@MRSInventarioBundle/Controller/AnexoController.php"
    type:     annotation

mrs_inventario_anexo:
    resource: "@MRSInventarioBundle/Controller/AnexoController.php"
    type:     annotation

mrs_inventario_anexo:
    resource: "@MRSInventarioBundle/Controller/AnexoController.php"
    type:     annotation

user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

mrs_user:
    resource: "@UserBundle/Resources/config/routing.yml"
mrs_inventario:
    resource: "@MRSInventarioBundle/Controller/"
    type:   annotation