mrs_backup_registro_anexo_backup:
    resource: "@MRSBackupBundle/Controller/RegistroAnexoBackupController.php"
    type:     annotation

mrs_backup_anexo_compartilhado:
    resource: "@MRSBackupBundle/Controller/AnexoCompartilhadoController.php"
    type:     annotation

mrs_backup_anexo_restore:
    resource: "@MRSBackupBundle/Controller/AnexoRestoreController.php"
    type:     annotation

mrs_backup_anexo_backup:
    resource: "@MRSBackupBundle/Controller/AnexoBackupController.php"
    type:     annotation

mrs_backup_registro_backup_equipamento:
    resource: "@MRSBackupBundle/Controller/RegistroBackupEquipamentoController.php"
    type:     annotation

mrs_backup_tipo_midia:
    resource: "@MRSBackupBundle/Controller/TipoMidiaController.php"
    type:     annotation

mrs_backup_job:
    resource: "@MRSBackupBundle/Controller/JobController.php"
    type:     annotation

mrs_backup_fita:
    resource: "@MRSBackupBundle/Controller/FitaController.php"
    type:     annotation

mrs_backup_job_servidor:
    resource: "@MRSBackupBundle/Controller/JobServidorController.php"
    type:     annotation

mrs_backup_job:
    resource: "@MRSBackupBundle/Controller/JobController.php"
    type:     annotation

mrs_backup_tipo_job:
    resource: "@MRSBackupBundle/Controller/TipoJobController.php"
    type:     annotation

mrs_backup_troca_fita:
    resource: "@MRSBackupBundle/Controller/TrocaFitaController.php"
    type:     annotation

mrs_backup_fita:
    resource: "@MRSBackupBundle/Controller/FitaController.php"
    type:     annotation

mrs_backup_registro_restore:
    resource: "@MRSBackupBundle/Controller/RegistroRestoreController.php"
    type:     annotation

mrs_backup_registro_backup:
    resource: "@MRSBackupBundle/Controller/RegistroBackupController.php"
    type:     annotation

mrs_backup_status:
    resource: "@MRSBackupBundle/Controller/StatusController.php"
    type:     annotation

mrs_backup_status:
    resource: "@MRSBackupBundle/Controller/StatusController.php"
    type:     annotation

mrs_backup_status:
    resource: "@MRSBackupBundle/Controller/StatusController.php"
    type:     annotation

mrs_backup_status:
    resource: "@MRSBackupBundle/Controller/StatusController.php"
    type:     annotation

mrs_backup:
    resource: "@MRSBackupBundle/Resources/config/routing.yml"
    prefix:   /

mrs_inventario_fornecedor_software:
    resource: "@MRSInventarioBundle/Controller/FornecedorSoftwareController.php"
    type:     annotation

mrs_inventario_custo_equipamento:
    resource: "@MRSInventarioBundle/Controller/CustoEquipamentoController.php"
    type:     annotation

mrs_inventario_status_ip:
    resource: "@MRSInventarioBundle/Controller/StatusIpController.php"
    type:     annotation

mrs_inventario_tipo_acesso_ip:
    resource: "@MRSInventarioBundle/Controller/TipoAcessoIpController.php"
    type:     annotation

mrs_inventario_endereco_ip:
    resource: "@MRSInventarioBundle/Controller/EnderecoIpController.php"
    type:     annotation

mrs_inventario_anexo_acompanhamento:
    resource: "@MRSInventarioBundle/Controller/AnexoAcompanhamentoController.php"
    type:     annotation

mrs_inventario_anexo:
    resource: "@MRSInventarioBundle/Controller/AnexoController.php"
    type:     annotation

mrs_inventario_anexo:
    resource: "@MRSInventarioBundle/Controller/AnexoController.php"
    type:     annotation

mrs_inventario_anexo:
    resource: "@MRSInventarioBundle/Controller/AnexoController.php"
    type:     annotation

user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

mrs_user:
    resource: "@UserBundle/Resources/config/routing.yml"
mrs_inventario:
    resource: "@MRSInventarioBundle/Controller/"
    type:   annotation