<?php

namespace MRS\BackupBundle\Repository;


use \Doctrine\ORM\EntityRepository;
/**
 * RegistroBackupEquipamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitaRepository extends EntityRepository
{

    public function listarQuantidadeUtilizadaByFita()
    {

        $query = "SELECT F.id, ciclo, jogo, bar_code, descricao,
                	(SELECT count(RES.id)
                	    FROM registro_restore AS RES
                	    WHERE RES.fita_id = F.id ) as 'restore',
                    (SELECT count(TROCA.id)
                        FROM troca_fita AS TROCA
                        WHERE TROCA.fita_id = F.id) as 'troca'
                  FROM fita AS F
                  ORDER BY unidade_id, descricao;";

        $stmt = $this->getEntityManager()
                     ->getConnection()
                     ->prepare($query);

        $stmt->execute();

        return $stmt->fetchAll();
    }

}
