<?php

namespace MRS\BackupBundle\Repository;

/**
 * RegistroBackupEquipamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroBackupEquipamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
