<?php

namespace MRS\BackupBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * RegistroBackupEquipamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroBackupRepository extends EntityRepository
{

    public function getMaxId()
    {
        return $this->createQueryBuilder('R')
            ->select('max(R.id)')
            ->getQuery()
            ->getSingleResult();
    }
}
