<?php

namespace MRS\BackupBundle\Repository;


use \Doctrine\ORM\EntityRepository;
/**
 * RegistroBackupEquipamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrocaFitaRepository extends EntityRepository
{

    public function getMaxId()
    {
        return $this->createQueryBuilder('T')
            ->select('max(T.id)')
            ->getQuery()
            ->getSingleResult();
    }

}
