<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxilxds\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxilxds/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHxilxds.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHxilxds\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHxilxds\appDevDebugProjectContainer([
    'container.build_hash' => 'Hxilxds',
    'container.build_id' => 'adc2dd98',
    'container.build_time' => 1617496837,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxilxds');
