<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRhaniei\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRhaniei/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRhaniei.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRhaniei\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRhaniei\appDevDebugProjectContainer([
    'container.build_hash' => 'Rhaniei',
    'container.build_id' => '9aec0a96',
    'container.build_time' => 1617549300,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRhaniei');
