<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC9binco\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC9binco/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC9binco.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC9binco\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC9binco\appDevDebugProjectContainer([
    'container.build_hash' => 'C9binco',
    'container.build_id' => 'da34301a',
    'container.build_time' => 1617540564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC9binco');
